version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: ecommerce-postgres
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  ecommerce-app:
    image: ecommerce-backend22
    container_name: ecommerce-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: ecommerce-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata: