version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: ecommerce-postgres
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: ecommerce-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata: