spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080