global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ecommerce-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ecommerce-app:8080']





#docker run -p 9090:9090 -v /Users/harinder/Downloads/ecommerce-backend22/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
